[package]
name = "solana-config-program"
version = "1.10.0"
description = "Solana Config program"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-config-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.136"
serde_derive = "1.0.103"
solana-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
solana-sdk = { path = "../../sdk", version = "=1.10.0" }

[dev-dependencies]
solana-logger = { path = "../../logger", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "solana_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
