[package]
name = "renec-config-program"
version = "1.8.14"
description = "RENEC Config program"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-config-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
log = "0.4.11"
rand_core = "0.6.2"
serde = "1.0.122"
serde_derive = "1.0.103"
solana-sdk = { path = "../../sdk", version = "=1.8.14" }

[dev-dependencies]
renec-logger = { path = "../../logger", version = "=1.8.14" }

[lib]
crate-type = ["lib"]
name = "renec_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
