[package]
name = "renec-sdk-macro"
version = "1.8.14"
description = "RENEC SDK Macro"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-sdk-macro"
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.3.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
