[package]
name = "solana-cargo-build-bpf"
version = "1.8.14"
description = "Compile a local package and all of its dependencies using the Solana BPF SDK"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
homepage = "https://remitano.com/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.3"
regex = "1.4.5"
cargo_metadata = "0.12.0"
solana-sdk = { path = "..", version = "=1.8.14" }
solana-download-utils = { path = "../../download-utils", version = "=1.8.14" }
tar = "0.4.37"

[dev-dependencies]
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
