[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
description = "Blockchain, Rebuilt for Scale"
edition = "2018"
homepage = "https://remitano.com/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/remitano/renec"
version = "1.8.14"

[workspace]

[dependencies]
tonic-build = "0.5.0"
