[package]
name = "renec-version"
version = "1.8.14"
description = "RENEC Version"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-version"
edition = "2018"

[dependencies]
log = "0.4.11"
serde = "1.0.122"
serde_derive = "1.0.103"
renec-frozen-abi = { path = "../frozen-abi", version = "=1.8.14" }
renec-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }

[lib]
name = "renec_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
