[package]
name = "solana-stake-program"
version = "1.10.0"
description = "Solana Stake program"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-stake-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.136"
serde_derive = "1.0.103"
solana-frozen-abi = { path = "../../frozen-abi", version = "=1.10.0" }
solana-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.10.0" }
solana-metrics = { path = "../../metrics", version = "=1.10.0" }
solana-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
solana-sdk = { path = "../../sdk", version = "=1.10.0" }
solana-vote-program = { path = "../vote", version = "=1.10.0" }
solana-config-program = { path = "../config", version = "=1.10.0" }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.0"
renec-logger = { path = "../../logger", version = "=1.10.0" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
