[package]
name = "renec-stake-program"
version = "1.8.14"
description = "RENEC Stake program"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-stake-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
log = "0.4.11"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.122"
serde_derive = "1.0.103"
renec-frozen-abi = { path = "../../frozen-abi", version = "=1.8.14" }
renec-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.8.14" }
renec-metrics = { path = "../../metrics", version = "=1.8.14" }
renec-sdk = { path = "../../sdk", version = "=1.8.14" }
renec-vote-program = { path = "../vote", version = "=1.8.14" }
renec-config-program = { path = "../config", version = "=1.8.14" }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.0"
renec-logger = { path = "../../logger", version = "=1.8.14" }

[build-dependencies]
rustc_version = "0.2"

[lib]
crate-type = ["lib"]
name = "renec_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
