[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "renec-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-validator"
default-run = "renec-validator"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.14.1"
core_affinity = "0.5.10"
fd-lock = "2.0.0"
indicatif = "0.15.0"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.11"
num_cpus = "1.13.0"
rand = "0.7.0"
serde = "1.0.112"
serde_json = "1.0.68"
renec-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
renec-cli-config = { path = "../cli-config", version = "=1.8.14" }
renec-client = { path = "../client", version = "=1.8.14" }
renec-core = { path = "../core", version = "=1.8.14" }
renec-download-utils = { path = "../download-utils", version = "=1.8.14" }
renec-faucet = { path = "../faucet", version = "=1.8.14" }
renec-genesis-utils = { path = "../genesis-utils", version = "=1.8.14" }
renec-gossip = { path = "../gossip", version = "=1.8.14" }
renec-ledger = { path = "../ledger", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
solana-metrics = { path = "../metrics", version = "=1.8.14" }
renec-net-utils = { path = "../net-utils", version = "=1.8.14" }
renec-perf = { path = "../perf", version = "=1.8.14" }
solana-poh = { path = "../poh", version = "=1.8.14" }
solana-rpc = { path = "../rpc", version = "=1.8.14" }
solana-runtime = { path = "../runtime", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-streamer = { path = "../streamer", version = "=1.8.14" }
renec-version = { path = "../version", version = "=1.8.14" }
renec-vote-program = { path = "../programs/vote", version = "=1.8.14" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"]}

[target."cfg(unix)".dependencies]
libc = "0.2.81"
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
