[package]
name = "renec-exchange-program"
version = "1.8.14"
description = "RENEC Exchange program"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-exchange-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
log = "0.4.11"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = "1.0.122"
serde_derive = "1.0.103"
renec-logger = { path = "../../logger", version = "=1.8.14" }
renec-metrics = { path = "../../metrics", version = "=1.8.14" }
renec-sdk = { path = "../../sdk", version = "=1.8.14" }
thiserror = "1.0"

[dev-dependencies]
renec-runtime = { path = "../../runtime", version = "=1.8.14" }

[lib]
crate-type = ["lib", "cdylib"]
name = "renec_exchange_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
