[package]
name = "solana-merkle-tree"
version = "1.8.14"
description = "RENEC Merkle Tree"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-merkle-tree"
edition = "2018"

[dependencies]
solana-program = { path = "../sdk/program", version = "=1.8.14" }
fast-math = "0.1"

# This can go once the BPF toolchain target Rust 1.42.0+
[target.bpfel-unknown-unknown.dependencies]
matches = "0.1.8"

[dev-dependencies]
hex = "0.4.2"

[lib]
crate-type = ["lib"]
name = "solana_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
