[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "renec-gossip"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-gossip"

[dependencies]
bincode = "1.3.1"
bv = { version = "0.11.1", features = ["serde"] }
clap = "2.33.1"
flate2 = "1.0"
indexmap = { version = "1.5", features = ["rayon"] }
itertools = "0.10.1"
log = "0.4.11"
lru = "0.7.1"
matches = "0.1.8"
num-traits = "0.2"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.0"
serde = "1.0.122"
serde_bytes = "0.11"
serde_derive = "1.0.103"
renec-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
renec-client = { path = "../client", version = "=1.8.14" }
renec-frozen-abi = { path = "../frozen-abi", version = "=1.8.14" }
renec-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.8.14" }
renec-ledger = { path = "../ledger", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
renec-measure = { path = "../measure", version = "=1.8.14" }
solana-metrics = { path = "../metrics", version = "=1.8.14" }
renec-net-utils = { path = "../net-utils", version = "=1.8.14" }
renec-perf = { path = "../perf", version = "=1.8.14" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.8.14" }
solana-runtime = { path = "../runtime", version = "=1.8.14" }
solana-streamer = { path = "../streamer", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
renec-version = { path = "../version", version = "=1.8.14" }
renec-vote-program = { path = "../programs/vote", version = "=1.8.14" }
renec-bloom = { path = "../bloom", version = "=1.8.14" }
thiserror = "1.0"

[dev-dependencies]
matches = "0.1.6"
num_cpus = "1.13.0"
serial_test = "0.4.0"

[build-dependencies]
rustc_version = "0.2"

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bin]]
name = "renec-gossip"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
