[package]
name = "solana-compute-budget-program"
description = "Solana Compute Budget program"
version = "1.10.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-compute-budget-program"
repository = "https://github.com/remitano/renec"
authors = ["RENEC Maintainers <dev@remitano.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
solana-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
solana-sdk = { path = "../../sdk", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "solana_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
