[package]
name = "renec-transaction-status"
version = "1.8.14"
description = "RENEC transaction status types"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-transaction-status"
license = "Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
bs58 = "0.3.1"
Inflector = "0.11.4"
lazy_static = "1.4.0"
log = "0.4.11"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
renec-account-decoder = { path = "../account-decoder", version = "=1.8.14" }
renec-measure = { path = "../measure", version = "=1.8.14" }
renec-metrics = { path = "../metrics", version = "=1.8.14" }
renec-sdk = { path = "../sdk", version = "=1.8.14" }
renec-runtime = { path = "../runtime", version = "=1.8.14" }
renec-vote-program = { path = "../programs/vote", version = "=1.8.14" }
spl-associated-token-account = { version = "=1.0.3", features = ["no-entrypoint"] }
spl-memo = { version = "=3.0.1", features = ["no-entrypoint"] }
spl-token = { version = "=3.2.0", features = ["no-entrypoint"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
