[package]
name = "renec-streamer"
version = "1.8.14"
description = "RENEC Streamer"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-streamer"
edition = "2018"

[dependencies]
itertools = "0.10.1"
log = "0.4.11"
solana-metrics = { path = "../metrics", version = "=1.8.14" }
renec-sdk = { path = "../sdk", version = "=1.8.14" }
thiserror = "1.0"
renec-measure = { path = "../measure", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
libc = "0.2.81"
nix = "0.20.0"
renec-perf = { path = "../perf", version = "=1.8.14" }

[dev-dependencies]

[lib]
crate-type = ["lib"]
name = "renec_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
