[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "solana-cli"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-cli"

[dependencies]
bincode = "1.3.1"
bs58 = "0.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
criterion-stats = "0.3.0"
ctrlc = { version = "3.1.5", features = ["termination"] }
console = "0.14.1"
const_format = "0.2.14"
dirs-next = "2.0.0"
log = "0.4.11"
Inflector = "0.11.4"
indicatif = "0.15.0"
humantime = "2.0.1"
num-traits = "0.2"
pretty-hex = "0.2.1"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
semver = "1.0.4"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
renec-account-decoder = { path = "../account-decoder", version = "=1.8.14" }
renec-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.8.14" }
renec-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
renec-cli-config = { path = "../cli-config", version = "=1.8.14" }
renec-cli-output = { path = "../cli-output", version = "=1.8.14" }
renec-client = { path = "../client", version = "=1.8.14" }
renec-config-program = { path = "../programs/config", version = "=1.8.14" }
renec-faucet = { path = "../faucet", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
solana-net-utils = { path = "../net-utils", version = "=1.8.14" }
solana_rbpf = "=0.2.21"
solana-remote-wallet = { path = "../remote-wallet", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-transaction-status = { path = "../transaction-status", version = "=1.8.14" }
renec-version = { path = "../version", version = "=1.8.14" }
renec-vote-program = { path = "../programs/vote", version = "=1.8.14" }
spl-memo = { version = "=3.0.1", features = ["no-entrypoint"] }
thiserror = "1.0.21"
tiny-bip39 = "0.8.1"
url = "2.1.1"

[dev-dependencies]
renec-core = { path = "../core", version = "=1.8.14" }
solana-streamer = { path = "../streamer", version = "=1.8.14" }
tempfile = "3.1.0"

[[bin]]
name = "solana"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
