[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "renec-genesis"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-genesis"

[dependencies]
base64 = "0.12.3"
clap = "2.33.1"
chrono = "0.4"
serde = "1.0.122"
serde_json = "1.0.56"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
solana-cli-config = { path = "../cli-config", version = "=1.8.14" }
solana-exchange-program = { path = "../programs/exchange", version = "=1.8.14" }
solana-ledger = { path = "../ledger", version = "=1.8.14" }
solana-logger = { path = "../logger", version = "=1.8.14" }
solana-runtime = { path = "../runtime", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-stake-program = { path = "../programs/stake", version = "=1.8.14" }
solana-version = { path = "../version", version = "=1.8.14" }
solana-vote-program = { path = "../programs/vote", version = "=1.8.14" }
tempfile = "3.1.0"

[[bin]]
name = "renec-genesis"
path = "src/main.rs"

[lib]
name = "renec_genesis"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
