[package]
name = "solana-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-stake-accounts"

[dependencies]
clap = "2.33.1"
renec-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
renec-cli-config = { path = "../cli-config", version = "=1.8.14" }
renec-client = { path = "../client", version = "=1.8.14" }
renec-remote-wallet = { path = "../remote-wallet", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
renec-stake-program = { path = "../programs/stake", version = "=1.8.14" }

[dev-dependencies]
solana-runtime = { path = "../runtime", version = "=1.8.14" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
