[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "solana-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-watchtower"

[dependencies]
clap = "2.33.1"
log = "0.4.11"
humantime = "2.0.1"
solana-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
solana-cli-config = { path = "../cli-config", version = "=1.8.14" }
solana-cli-output = { path = "../cli-output", version = "=1.8.14" }
solana-client = { path = "../client", version = "=1.8.14" }
solana-logger = { path = "../logger", version = "=1.8.14" }
solana-metrics = { path = "../metrics", version = "=1.8.14" }
solana-notifier = { path = "../notifier", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-version = { path = "../version", version = "=1.8.14" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
