[package]
name = "solana-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.14.1"
csv = "1.1.3"
ctrlc = { version = "3.1.5", features = ["termination"] }
dirs-next = "2.0.0"
indexmap = "1.5.1"
indicatif = "0.15.0"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
renec-account-decoder = { path = "../account-decoder", version = "=1.8.14" }
renec-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
renec-cli-config = { path = "../cli-config", version = "=1.8.14" }
renec-client = { path = "../client", version = "=1.8.14" }
solana-remote-wallet = { path = "../remote-wallet", version = "=1.8.14" }
solana-runtime = { path = "../runtime", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-transaction-status = { path = "../transaction-status", version = "=1.8.14" }
renec-version = { path = "../version", version = "=1.8.14" }
spl-associated-token-account = { package = "spl-associated-token-account", version = "=1.0.3" }
spl-token = { version = "=3.2.0", features = ["no-entrypoint"] }
tempfile = "3.1.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.1"
solana-core = { path = "../core", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
solana-program-test = { path = "../program-test", version = "=1.8.14" }
solana-streamer = { path = "../streamer", version = "=1.8.14" }
