[package]
name = "solana-secp256k1-program"
description = "Solana Secp256k1 program"
version = "1.8.14"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-secp256k1-program"
repository = "https://github.com/remitano/renec"
authors = ["RENEC Maintainers <dev@remitano.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
solana-sdk = { path = "../../sdk", version = "=1.8.14" }

[dev-dependencies]
bincode = "1.3.1"
libsecp256k1 = "0.5.0"
rand = "0.7.0"
solana-logger = { path = "../../logger", version = "=1.8.14" }

[lib]
crate-type = ["lib"]
name = "solana_secp256k1_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
