[package]
name = "solana-storage-proto"
version = "1.8.14"
description = "RENEC Storage Protobuf Definitions"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-storage-proto"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
prost = "0.8.0"
serde = "1.0.122"
serde_derive = "1.0.103"
renec-account-decoder = { path = "../account-decoder", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-transaction-status = { path = "../transaction-status", version = "=1.8.14" }

[dev-dependencies]
enum-iterator = "0.6.0"

[lib]
crate-type = ["lib"]
name = "solana_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.5.0"
