[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "solana-stake-monitor"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-stake-monitor"

[dependencies]
clap = "2.33.1"
console = "0.14.1"
log = "0.4.11"
serde = "1.0.122"
serde_yaml = "0.8.13"
renec-clap-utils = { path = "../clap-utils", version = "=1.8.14" }
renec-cli-config = { path = "../cli-config", version = "=1.8.14" }
renec-client = { path = "../client", version = "=1.8.14" }
renec-logger = { path = "../logger", version = "=1.8.14" }
solana-metrics = { path = "../metrics", version = "=1.8.14" }
solana-rpc = { path = "../rpc", version = "=1.8.14" }
solana-sdk = { path = "../sdk", version = "=1.8.14" }
solana-transaction-status = { path = "../transaction-status", version = "=1.8.14" }
renec-version = { path = "../version", version = "=1.8.14" }

[dev-dependencies]
serial_test = "0.4.0"
solana-local-cluster = { path = "../local-cluster", version = "=1.8.14" }
renec-core = { path = "../core", version = "=1.8.14" }
tempfile = "3.1.0"

[[bin]]
name = "solana-stake-monitor"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
