[package]
name = "renec-cargo-test-bpf"
version = "1.8.14"
description = "Execute all unit and integration tests after building with the RENEC BPF SDK"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
homepage = "https://remitano.com/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.12.0"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
