[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "solana-scripts"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
publish = false

[dependencies]
csv = "1.1"
serde = { version = "1.0.122", features = ["derive"] }

[[bin]]
name = "solana-csv-to-validator-infos"
path = "src/csv_to_validator_infos.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
