[package]
name = "renec-storage-bigtable"
version = "1.8.14"
description = "RENEC Storage BigTable"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-storage-bigtable"
edition = "2018"

[dependencies]
arc-swap = "0.4.8"
backoff = { version = "0.3.0", features = ["tokio"] }
bincode = "1.2.1"
bzip2 = "0.3.3"
enum-iterator = "0.6.0"
flate2 = "1.0.14"
goauth = "0.10.0"
log = "0.4.11"
prost = "0.8.0"
prost-types = "0.8.0"
rand_core = "0.6.2"
serde = "1.0.122"
serde_derive = "1.0.103"
smpl_jwt = "0.6.1"
solana-metrics = { path = "../metrics", version = "=1.8.14" }
renec-sdk = { path = "../sdk", version = "=1.8.14" }
renec-storage-proto = { path = "../storage-proto", version = "=1.8.14" }
renec-transaction-status = { path = "../transaction-status", version = "=1.8.14" }
thiserror = "1.0"
futures = "0.3.8"
tonic = { version = "0.5.0", features = ["tls", "transport"] }
zstd = "0.5.1"

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { version = "0.10", features = [] }

[lib]
crate-type = ["lib"]
name = "renec_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
