[package]
name = "renec-upload-perf"
version = "1.8.14"
description = "Metrics Upload Utility"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
edition = "2018"
homepage = "https://remitano.com/"
publish = false

[dependencies]
serde_json = "1.0.56"
solana-metrics = { path = "../metrics", version = "=1.8.14" }

[[bin]]
name = "renec-upload-perf"
path = "src/upload-perf.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
