[package]
name = "renec-ed25519-program"
description = "RENEC Ed25519 program"
version = "1.8.14"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-ed25519-program"
repository = "https://github.com/remitano/renec"
authors = ["RENEC Maintainers <dev@remitano.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
renec-sdk = { path = "../../sdk", version = "=1.8.14" }

[dev-dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
ed25519-dalek = "=1.0.1"
rand = "0.7.0"
renec-logger = { path = "../../logger", version = "=1.8.14" }

[lib]
crate-type = ["lib"]
name = "renec_ed25519_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
