[package]
name = "renec-bpf-rust-sysvar"
version = "1.8.14"
description = "RENEC BPF test program written in Rust"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-bpf-rust-sysvar"
edition = "2018"

[dependencies]
renec-program = { path = "../../../../sdk/program", version = "=1.8.14" }

[dev-dependencies]
renec-program-test = { path = "../../../../program-test", version = "=1.8.14" }
solana-sdk = { path = "../../../../sdk", version = "=1.8.14" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
