[package]
name = "solana-send-transaction-service"
version = "1.10.0"
description = "Solana send transaction service"
authors = ["RENEC Maintainers <dev@remitano.com>"]
repository = "https://github.com/remitano/renec"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/solana-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.14"
solana-metrics = { path = "../metrics", version = "=1.10.0" }
solana-runtime = { path = "../runtime", version = "=1.10.0" }
solana-sdk = { path = "../sdk", version = "=1.10.0" }

[dev-dependencies]
solana-logger = { path = "../logger", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
