[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2018"
name = "solana-store-tool"
description = "Tool to inspect append vecs"
version = "1.8.14"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
publish = false

[dependencies]
log = { version = "0.4.11" }
renec-logger = { path = "../../logger", version = "=1.8.14" }
renec-version = { path = "../../version", version = "=1.8.14" }
renec-measure = { path = "../../measure", version = "=1.8.14" }
solana-runtime = { path = "..", version = "=1.8.14" }
solana-sdk = { path = "../../sdk", version = "=1.8.14" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
